services:
  anime-sage:
    build: .
    container_name: anime_sage_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./anime_sage_session.session:/app/anime_sage_session.session
    environment:
      - PYTHONUNBUFFERED=1